version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=my_database
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
